### ISSUE TITLE
Upgrade to Beautiful Soup 4.4.0 breaks tests

### ISSUE THREAD

**Issue by stt** [pbs/pycaption#115]
test_srt_to_dfxp_conversion and test_webvtt_to_dfxp_conversion fail with AssertionError.
The expected value contains 
```html
<span tts:textalign="right">we have this vision of Einstein</span>
```
although DFXPTestingMixIn should be removing spans.

**Comment by vladiibine** [comment]
This doesn't look like it's happening any more. Closing the ticket

**Comment by vladiibine** [comment]
So I checked this again, and funny enough, this issue appears if you're using beautifulsoup4==4.4.0, BUT not beautifulsoup==4.4.1

I'd reccomend using the latter version. 
Thanks for the feedback. I'll integrate your pull request, because it's a good idea for the tests to run for everyone :)
