### ISSUE TITLE
Does not allow cue without content (in webvtt)?

### ISSUE THREAD

**Issue by avinassh** [pbs/pycaption#129]
Following is the sample WebVTT file I have:

```
WEBVTT

Id 72
11:01:15.200 --> 11:01:16.201
Some Subtitle - 1 

NOTE
{
"message": "some note"
}

Mark 72
12:01:15.200 --> 12:01:16.201

NOTE
{
"message": "some note"
}
```

It is actually valid if you check here: https://quuz.org/webvtt/

However I am getting an error:

```
CaptionReadSyntaxError: CaptionReadSyntaxError(('Cue without content. (line 12)',))
```

**Comment by ana-nichifor** [comment]
Starting with 1.0.4 pycaption is no longer raising errors for empty webvtt cues, it just ignores them. Regarding notes, this functionality is not implemented, they are treated as regular text.

**Comment by avinassh** [comment]
hey @ana-nichifor, feel free to close this issue
