### ISSUE TITLE
'pip install pycaption --upgrade' doesn't pull latest pycaption code updates.

### ISSUE THREAD

**Issue by hvedamurthy** [pbs/pycaption#132]
I tried to upgrade your latest pycaption to my machine:
`pip install pycaption --upgrade`
`Requirement already up-to-date: pycaption in /usr/local/lib/python2.7/site-packages/pycaption-0.5.4-py2.7.egg`
`Requirement already up-to-date: beautifulsoup4>=4.2.1 in /usr/local/lib/python2.7/site-packages/beautifulsoup4-4.4.1-py2.7.egg (from pycaption)`
`Collecting lxml>=3.2.3 (from pycaption)`
 ` Downloading lxml-3.5.0.tar.gz (3.8MB)`
   ` 100% |████████████████████████████████| 3.8MB 132kB/s `
`Requirement already up-to-date: cssutils>=0.9.10 in /usr/local/lib/python2.7/site-packages/cssutils-1.0.1-py2.7.egg (from pycaption)`
`Installing collected packages: lxml`
 ` Found existing installation: lxml 3.5.0b1`
   ` Uninstalling lxml-3.5.0b1:`
      `Successfully uninstalled lxml-3.5.0b1`
  `Running setup.py install for lxml`
`Successfully installed lxml-3.5.0`
`You are using pip version 7.1.2, however version 8.0.2 is available.`
`You should consider upgrading via the 'pip install --upgrade pip' command.`

It does upgrade lxml changes, but it did not upgrade the pycaption package itself. See above it says **"Requirement already up-to-date: pycaption in /usr/local/lib/python2.7/site-packages/pycaption-0.5.4-py2.7.egg".**

We require your latest change for Work around for lack of `'&apos;'` support in html.parser. Your PR# https://github.com/pbs/pycaption/pull/124.

Kindly look into this issue and let us know if you could get around to package latest pycaption changes to pip, asap. Our internal automated system that uses pycaption requires the latest change. It would be of great help. Thanks in advance!

**Comment by vladiibine** [comment]
Hey,

I'll release version 0.5.5

**Comment by hvedamurthy** [comment]
Thank you!
