### ISSUE TITLE
Caption writer per language

### ISSUE THREAD

**Issue by byumark** [pbs/pycaption#136]
This is more of a question than an issue. I've been trying to write one SRT per language that exists inside of a DFXP.  So if the DFXP has 5 languages, I'd like to end up with 5 different SRTs.  With the get_languages and get_captions methods it seemed like it would be doable but get_captions is returning a CaptionList that doesn't translate to a CaptionSet. Or at least I can't seem to figure it out.  And it seems that a writer only accepts a CaptionSet.

Any thoughts? Sorry if this isn't the right place to post this.

**Comment by byumark** [comment]
I forked this repository and created a solution to handle this.  I am unfamiliar with the process of trying to get the new code implemented into the main repository.  What is the best way to do this?  Create a pull request? I want to avoid overstepping my bounds.

**Comment by jamesturk** [comment]
Hi, thanks for the report and glad you got this figured out. 

Right now the team that maintains this is stretched a bit thin so we may not be able to review it in as timely fashion as we'd like but if you can create a PR we'd definitely appreciate it and can try to review it as soon as we get a chance.
