### ISSUE TITLE
SRTReader CaptionReadNoCaptions on Spanish .srt file

### ISSUE THREAD

**Issue by dgirgenti** [pbs/pycaption#148]
I am currently doing a large-scale conversion of .srt to .vtt files. I have been successfully using pycaption 1.0.0 for months, and all of a sudden today one .srt file is just not working. 

The code that has worked up to this point looks like this:
```
with open(tmp_srt_file, 'rU') as srt_file:
    converter = CaptionConverter()
    converter.read(srt_file.read().decode('utf-8'), SRTReader())
    vtt = converter.write(WebVTTWriter())
    return vtt
```

It is failing on the converter.read() (NOT the decode to utf8) with `CaptionReadNoCaptions(('empty caption file',))`.

If I `print srt_file.read().decode('utf-8')` it looks like it should look.

Unfortunately, I can't share this specific file as I am under NDA with a client. However, I can comment that as far as I can tell, there are no special characters. It looks like any other .srt file I have worked with. I have certainly seen weirder .srt files that worked.

Is there something I should be looking for, or is this potentially a real issue?

**Comment by Ldream** [comment]
try use chardet
`
def converByName(path,fileName):
    ans = (fileName,None)
    if(fileName.split('.')[-1] != "srt"):
        return ans
    convertFilePath = os.path.join(path,fileName)
#     print("Start convert " + convertFilePath)
    try:
        converter = CaptionConverter()
        import chardet
        import codecs
        deChar = {}
        with open(convertFilePath,'rb') as f:
            deChar = chardet.detect(f.read())
            #print(deChar)
            if deChar['encoding'] == 'UTF-16LE':
                deChar['encoding'] = 'UTF-16'
        with codecs.open(convertFilePath,'r',encoding=deChar['encoding']) as f:
            k = f.read().strip('\n').replace('.',',')
            k = k.encode().decode()
            converter.read(k, SRTReader())
            vtt = converter.write(WebVTTWriter())
        ans = (fileName,1,deChar['encoding'])
        return ans
    except:
        print(convertFilePath)
        traceback.print_exc()
        return (fileName,None,deChar['encoding'])
`

**Comment by dgirgenti** [comment]
I can't remember which but it was either an encoding or syntax issue, closing.
