### ISSUE TITLE
Can BeautifulSoup4 dependency be relaxed?

### ISSUE THREAD

**Issue by z4y4ts** [pbs/pycaption#151]
Hi,

I'm using pycaption library in a quite outdated and rigid environment. In short, it's a plugin for a large application, Python 2.7 & parent application has `BeautifulSoup4==4.1.3` pinned & installed.

Is it possible to relax pycaption requirements from `beautifulsoup4<4.5.0,>=4.2.1` to `beautifulsoup4<4.5.0,>=4.1.3`?

Of course, I'm talking about "0.x" branch.

Other suggestions are much appreciated.

Best regards,
Alexander

**Comment by ana-nichifor** [comment]
Hi, I'm not sure what branch are you referring to, could you tell me its full name?
