### ISSUE TITLE
Getting error that the "command not found"

### ISSUE THREAD

**Issue by webunraveling** [pbs/pycaption#155]
I've installed from source, using python 3.5.3 on Debian 9. Trying to get pycaption 1.0.0 working. Since it appears to have actually installed in to /usr/local/lib/python3.5/dist-packages/ it is also getting picked up for autofilling when I hit the tab key in the terminal. Unfortunately, when I run the command I get the error message `bash: pycaption: command not found`. Sometimes `pip` takes care of installing things better than I can from source, so I installed `python3-pip` and installed pycaption with `pip install pycaption` which also takes care of any missing deps. Yet, no matter what I do, it seems to continue giving me the error that the command does not exist.

If its at all helpful, here is the output from installing with `pip`.

    $ sudo pip3 install pycaption
    Collecting pycaption
        Downloading pycaption-1.0.0.tar.gz (219kB)
            100% |████████████████████████████████| 225kB 1.6MB/s
    Requirement already satisfied: beautifulsoup4<4.5.0,>=4.2.1 in /usr/local/lib/python3.5/dist-packages (from pycaption)
    Requirement already satisfied: cssutils>=0.9.10 in /usr/local/lib/python3.5/dist-packages (from pycaption)
    Requirement already satisfied: enum34 in /usr/local/lib/python3.5/dist-packages (from pycaption)
    Requirement already satisfied: future in /usr/local/lib/python3.5/dist-packages (from pycaption)
    Requirement already satisfied: lxml>=3.2.3 in /usr/local/lib/python3.5/dist-packages (from pycaption)
    Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from pycaption)
    Building wheels for collected packages: pycaption
        Running setup.py bdist_wheel for pycaption ... done
        Stored in directory: /root/.cache/pip/wheels/b2/ce/63/e1e9340d28f6e251e18e2b706d03866df2f501287f174298ab
    Successfully built pycaption
    Installing collected packages: pycaption
    Successfully installed pycaption-1.0.0

**Comment by webunraveling** [comment]
I am suspecting that this has something to do with my environment. I'll wait to see if anyone else is experiencing the same thing.

**Comment by enzanki-ars** [comment]
pycaption does not provide a cli interface.  Sadly, I have not found one that works well yet.  Might write my own...

**Comment by webunraveling** [comment]
@enzanki-ars thanks for the reply. This is kind of blowing my mind because I had a VM setup with pycaption running on Debian and only used it in BASH. I even wrote some BASH scripts that used pycaption. Unfortunately, that VM disappeared one day along with however I got pycaption to run in BASH. I suspect it was one of two things. It could have been antivirus software.... or, now after learning there is no CLI, someone traveled back in time and whatever changes in history they made caused a CLI not to be made and also my VM to never come into existence. For whatever reason, I'm the only one who has a faint memory of it.

Either way, I guess this issue can be marked as solved.

**Comment by webunraveling** [comment]
Since it had been so long since I installed it I forgot that I had found a different repo: [pycaption-cli](https://github.com/jnorton001/pycaption-cli) that I had been using.
