### ISSUE TITLE
SCC ascii Error

### ISSUE THREAD

**Issue by AlexEKoren** [pbs/pycaption#157]
I have an SCC file which includes a line in it with a "é" in it. Here's the exact snippet:

> Scenarist_SCC V1.0
> 
> 01:46:04:21	9420 9420 9470 9470 97a2 97a2 e9f4 206d ef76 e564 2061 f2ef 756e 6420 f468 e520 e3ef f26e e5f2 ae80 942c 942c 942f 942f
> 
> 01:46:06:11	9420 9420 9452 9452 9723 9723 acdc c1ce ba80 91ae 91ae 91b3 91b3 5175 dc20 7061 7361 bf80 9120 9120 94f2 94f2 97a2 97a2 adc1 20e6 e5f7 2062 ecef e36b 7320 64ef f76e ae80 942c 942c 942f 942f
> 
> 01:46:08:09	9420 9420 9454 9454 9723 9723 ad4f 6e20 3734 f468 ae80 94f4 94f4 91ae 91ae add6 616d ef73 2c20 4a61 6de9 e5ae 942c 942c 942f 942f

and the error:

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

Any ideas?

**Comment by ana-nichifor** [comment]
Hi @AlexEKoren ! This doesn't seem to reproduce anymore so I'll close this issue.
