### ISSUE TITLE
Heuristic checking for standalone EOC marker in the SCC fails on valid SCC

### ISSUE THREAD

**Issue by sannies** [pbs/pycaption#168]
I got music movie captioning with very short captions 'Wah-wah-wan' and the check in pycaption/scc/__init__.py#229...332

        for cap in captions.get_captions(lang):
            # if there's an end time on a caption and the difference is
            # less than .05s kill it (this is likely caused by a standalone
            # EOC marker in the SCC file)
            if 0 < cap.end - cap.start < 50000:
                raise ValueError('unsupported length found in SCC input file: ' + str(cap))

fails. 
This check doesn't add any value in my eyes and should be removed completely

**Comment by ana-nichifor** [comment]
This error cannot be removed at the moment because it handles an unsolved issue with flashing captions.
