### ISSUE TITLE
Inverted Frame Order with SCCWriter when Converting from SRT

### ISSUE THREAD

**Issue by dshen94** [pbs/pycaption#171]
We've been running into issues consistently when trying to convert SRT files to SCC where the output file would have captions with inverted frame ordering where a later frame would appear in the caption first, like the following:

> 00:03:25:15	94ae 94ae 9420 9420 94d0 94d0 3e3e 2054 68e5 20e3 ef6e f4e5 6ef4 20ef e620 6d79 20f7 eff2 6b73 2068 6173 9470 9470 73e5 76e5 f261 ec20 73ef 75f2 e3e5 7320 efe6 20e9 6e73 70e9 f261 f4e9 ef6e ae80 942c 942c 942f 942f

>**00:03:30:18**	94ae 94ae 9420 9420 94d0 94d0 5468 e520 e6e9 f273 f420 e973 206d 7920 70e5 f273 ef6e 61ec 9470 9470 6261 e36b 67f2 ef75 6e64 ae80 942c 942c 942f 942f

>**00:03:30:17**	94ae 94ae 9420 9420 13d0 13d0 5468 e520 e6e9 f273 f420 e973 206d 7920 70e5 f273 ef6e 61ec 1370 1370 6261 e36b 67f2 ef75 6e64 94d0 94d0 6173 2049 20ec e561 f26e e564 20f4 f261 64e9 f4e9 ef6e 61ec 9470 9470 7061 e96e f4e9 6e67 2c80 942c 942c 942f 942f

>00:03:37:17	94ae 94ae 9420 9420 1370 1370 6173 2061 20e3 68e9 ec64 2061 6e64 20e9 f4a7 7320 6e61 f475 f261 ec20 e6ef f280 94d0 94d0 6de5 20f4 ef20 7573 e564 20f4 68e5 73e5 20e3 ef64 e573 20f4 ef80 9470 9470 e5f8 70f2 e573 7320 6d79 73e5 ece6 ae80 942c 942c 942f 942f

which is converted from the following SRT snippet

34
00:03:27,169 --> 00:03:31,831
The content of my works has
several sources of inspiration.

35
00:03:31,831 --> 00:03:32,460
The first is my personal background.

36
00:03:32,460 --> 00:03:39,516
The first is my personal background
as I learned traditional painting,

It's causing issues with certain dvd mastering software and we were wondering if it's a bug with the writer, or just the mastering software.

Thanks.

**Comment by ana-nichifor** [comment]
Hi, I translated the SCC using `pycaption.translate_scc` and the output is the following:
`00:03:25:15 [Erase Non-displayed Memory] [Erase Non-displayed Memory] [Resume Caption Loading] [Resume Caption Loading] [row 14, column 00, with plain white text.] [row 14, column 00, with plain white text.] [>>] [ T] [he] [ c] [on] [te] [nt] [ o] [f ] [my] [ w] [or] [ks] [ h] [as] [row 15, column 00, with plain white text.] [row 15, column 00, with plain white text.] [se] [ve] [ra] [l ] [so] [ur] [ce] [s ] [of] [ i] [ns] [pi] [ra] [ti] [on] [.] [Erase Displayed Memory] [Erase Displayed Memory] [End Of Caption] [End Of Caption]

00:03:30:18 [Erase Non-displayed Memory] [Erase Non-displayed Memory] [Resume Caption Loading] [Resume Caption Loading] [row 14, column 00, with plain white text.] [row 14, column 00, with plain white text.] [Th] [e ] [fi] [rs] [t ] [is] [ m] [y ] [pe] [rs] [on] [al] [row 15, column 00, with plain white text.] [row 15, column 00, with plain white text.] [ba] [ck] [gr] [ou] [nd] [.] [Erase Displayed Memory] [Erase Displayed Memory] [End Of Caption] [End Of Caption]

00:03:30:17 [Erase Non-displayed Memory] [Erase Non-displayed Memory] [Resume Caption Loading] [Resume Caption Loading] [row 12, column 00, with plain white text.] [row 12, column 00, with plain white text.] [Th] [e ] [fi] [rs] [t ] [is] [ m] [y ] [pe] [rs] [on] [al] [row 13, column 00, with plain white text.] [row 13, column 00, with plain white text.] [ba] [ck] [gr] [ou] [nd] [row 14, column 00, with plain white text.] [row 14, column 00, with plain white text.] [as] [ I] [ l] [ea] [rn] [ed] [ t] [ra] [di] [ti] [on] [al] [row 15, column 00, with plain white text.] [row 15, column 00, with plain white text.] [pa] [in] [ti] [ng] [,] [Erase Displayed Memory] [Erase Displayed Memory] [End Of Caption] [End Of Caption]

00:03:37:17 [Erase Non-displayed Memory] [Erase Non-displayed Memory] [Resume Caption Loading] [Resume Caption Loading] [row 13, column 00, with plain white text.] [row 13, column 00, with plain white text.] [as] [ a] [ c] [hi] [ld] [ a] [nd] [ i] [t'] [s ] [na] [tu] [ra] [l ] [fo] [r] [row 14, column 00, with plain white text.] [row 14, column 00, with plain white text.] [me] [ t] [o ] [us] [ed] [ t] [he] [se] [ c] [od] [es] [ t] [o] [row 15, column 00, with plain white text.] [row 15, column 00, with plain white text.] [ex] [pr] [es] [s ] [my] [se] [lf] [.] [Erase Displayed Memory] [Erase Displayed Memory] [End Of Caption] [End Of Caption]
`

So the order of the resulted SRT seems to respect the SCC content. Could you provide more details on what is wrong and what is the expected output?
