### ISSUE TITLE
For DFXP files, detects captions with "<tt>" only

### ISSUE THREAD

**Issue by prabhakar267** [pbs/pycaption#173]
According to the latest w3 DFXP specs, `<tt>` and `<tt:tt>` both are acceptable formats for a valid DFXP file.
Specs: https://www.w3.org/TR/ttml1/#document-structure-vocabulary-tt

**Comment by ana-nichifor** [comment]
Hi, can you provide more details on the use case of <tt:tt>? Are there any benefits over simple <tt> tags? Are there situations where tt is required as a namespace?

**Comment by ana-nichifor** [comment]
I'm going to close this issue and we can continue the conversation on #213 as it addresses the same problem with more details. Thank you!
