### ISSUE TITLE
SCC file content error

### ISSUE THREAD

**Issue by anssandeep** [pbs/pycaption#183]
I tried to read a SCC file and print the content, the content looks repetitive

(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?
(Client's Voice)\nRemember that degree\nyou got in taxation?

[TV1_HC47974.txt](https://github.com/pbs/pycaption/files/2863380/TV1_HC47974.txt)

Could you please let me know the issue.

**Comment by pacifier1er** [comment]
Hi @anssandeep , sorry for the delay, this is a known issue when mixing roll-up captions with paint-on or pop-on captions.  The reader keeps looking for the next roll-up command and each time a command to print the caption to the screen is encountered the most recent roll-up caption is printed in place of the pop-on caption.

Until a fix is available the best thing to do is ensure all captions are of the same format.  For pre-recorded content pop-on is usually preferred as it allows precise placement and styling.
