### ISSUE TITLE
FATAL BUG in parsing scc

### ISSUE THREAD

**Issue by arianaa30** [pbs/pycaption#184]
I realized the library has issues parsing scc files containing `9429` code (Paint On code). Anyways, it can not parse this standard scc file:
[test.zip](https://github.com/pbs/pycaption/files/2916381/test.zip)

**Some please fix this bug.**

There are hundreds of files like this. We assumed pycaption is able to understand standard SCC codes: http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CODES.HTML

**Comment by arianaa30** [comment]
@webunraveling

**Comment by arianaa30** [comment]
@dgirgenti

**Comment by Iulia-Mada** [comment]
@arianaa30 Would you help me with more context please? I want to understand how did you test it. I used SCCReader to read text.scc and it looks fine.
