### ISSUE TITLE
DFXPWriter adding an extra character to the tt tag

### ISSUE THREAD

**Issue by allensmith81** [pbs/pycaption#198]
Hi all,

Everytime I am converting vtt to DFXPwriter using command like:

`OutPutFile.write(DFXPWriter().write(reader().read(ImportData)))`

I get an extra character which fails when i try to validate the resulting .ttml file, specifically:

`<tt xml:lang="en" xmlns:="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">`

after xmlns there should be no ':' so it should be 
`<tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
`
I tried to see if I could see what was adding it in your code but I am not seeing it, any thoughts?

**Comment by allensmith81** [comment]
So a little bit more digging it seems this is done in Beautifulsoup 4.. have not yet figured out why.

If you use this code:

`from bs4 import BeautifulSoup
DFXP_BASE_MARKUP = '''
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling">
    <head>
        <styling/>
        <layout/>
    </head>
    <body/>
</tt>
'''
print(BeautifulSoup(DFXP_BASE_MARKUP, 'lxml-xml'))

you get the same result`

**Comment by ana-nichifor** [comment]
Hi, thanks for reporting this! Today we released pycaption 1.0.4 in which we upgraded the BeautifulSoup version and this issue was fixed.
