### ISSUE TITLE
Project status update request

### ISSUE THREAD

**Issue by abn** [pbs/pycaption#200]
Came across the project as part of packaging a project that depends on this one. Was hoping to get an update on whether this project is still intended to be maintained etc.

I can see that https://github.com/castlabs/pycaption is the most recent/active fork worked on by @sannies. If @pbs is not actively maintaining the project would it make sense to provide maintainer rights or ownership to a community member can contribute to the project. Would be great to avoid having to publish a new package altogether on PyPI.

Would also be happy to provide PRs (there are already a few stale ones) if someone from @pbs is able to review/merge.

**Comment by ana-nichifor** [comment]
Hi @abn , thanks for your interest! We plan to revive this project and bring it up to date. Right now we are going through pull requests and reviewing them. Your contributions will be welcome as well!
