### ISSUE TITLE
pycaption cannot cope with subtitles in dfxp format if they contain a namespace

### ISSUE THREAD

**Issue by HaydonBerrow** [pbs/pycaption#213]
pycaption cannot cope with subtitles in dfxp format if they contain a namespace
[Unforgotten-episode-xx.en.dfxp.txt](https://github.com/pbs/pycaption/files/6285531/Unforgotten-episode-xx.en.dfxp.txt)

This command will produce an example (episode 6 of UK-programme 'Unforgotten', previous episodes didn't use a namespace)

youtube-dl --skip-download --write-srt --sub-lang en -o Unforgotten-episode-xx.mp4 -f hls-2172-2 https://player.stv.tv/episode/42m5/unforgotten

and the file starts with

<?xml version="1.0" encoding="UTF-8"?>
<tt:tt xmlns:tt="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xml:space="preserve" ttp:timeBase="smpte" ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:dropMode="nonDrop" ttp:cellResolution="50 30" tts:extent="720px 576px" xml:lang="en-GB">
	<tt:head xmlns:ttm="http://www.w3.org/ns/ttml#metadata">

The issue first arises at line 72 in 
pycaption-1.1.0-py3.8.egg/pycaption/dfxp/base.py

with the code
        for div in dfxp_document.find_all('div'):
because the correct element is still/now '<tt:div>'

**Comment by ana-nichifor** [comment]
Hi, can you provide more details on the use case of `<tt:tt>`? Are there any benefits over simple `<tt>` tags? Are there situations where tt is required as a namespace?

**Comment by HaydonBerrow** [comment]
Sorry, namespaces in XML files are _terra incognita_ to me. I have no idea why this site (player.stv.tv) adds them but I have since found multiple instances of it. I get around it by editing the dfxp file.
