### ISSUE TITLE
SRT test failure

### ISSUE THREAD

**Issue by shahriman** [pbs/pycaption#22]
I ran `python -m unittest test_srt_conversion` and got [this](https://gist.github.com/shahriman/8735278).

May be it's specific to my BeautifulSoup / libxml version? I have
beautifulsoup4==4.3.2
lxml==2.3.2
libxml2 version: 2.7.8.dfsg-5.1ubuntu4.6

**Comment by vladiibine** [comment]
Hi @shahriman , are you still having problems with this?
I know it's a little late, but a lot of things have happened to pycaption, and a lot of linux libraries are current. 

Let me know so I can close the issue.

-vlad

**Comment by shahriman** [comment]
You can close this.
