### ISSUE TITLE
Support lxml 4.9

### ISSUE THREAD

**Issue by nyuszika7h** [pbs/pycaption#291]
lxml 4.8.x contains a [security vulnerability](https://github.com/advisories/GHSA-wrxv-2j5q-m38w) that's fixed in 4.9.1, but pycaption having it pinned to `<4.9` is currently preventing me from updating it to fix the vulnerability. Please consider adding support for 4.9.x soon.

**Comment by rlaphoenix** [comment]
+1

**Comment by dyudyunov** [comment]
+1
