### ISSUE TITLE
Requirements upgrade

### ISSUE THREAD

**Issue by dyudyunov** [pbs/pycaption#293]
Please, update the requirements to use the latest versions of the packages:
- Beautifulsoup <=4.11.1 (https://pypi.org/project/beautifulsoup4/)
- cssutils <=2.5.1 (https://pypi.org/project/cssutils/) **NOTE:** It requires python 3.7 from the version 2.4.0
- lxml (#291)

**Comment by dyudyunov** [comment]
@ana-nichifor could you take a look?

We're highly dependent on this issue. The https://github.com/raccoongang/xblock-video/issues/551 is blocked until this one is resolved

**Comment by dVeza** [comment]
Unfortunately @ana-nichifor is no longer actively working on pycaption. 
I will try to help with more pressing issues only, for now, starting on this.
Thanks for the reminder.
