### ISSUE TITLE
SUPPORTED_WRITERS to parallel SUPPORTED_READERS

### ISSUE THREAD

**Issue by acdha** [pbs/pycaption#30]
I wanted a dictionary similar to `SUPPORTED_READERS` to make it simple to have a conversion tool a text name to lookup the writer class to use — e.g. `--output-format=webvtt`. This is obviously pretty easy to handle but it means I have a hard-coded list which would be nice to avoid:

https://gist.github.com/acdha/c9fd54d4dee67801a09b#file-convert-subtitles-py-L24-L30

**Comment by pacifier1er** [comment]
We currently don't have plans to add new writers so a hard-coded list is probably ok to use.  Thanks.
