### ISSUE TITLE
SCC timing query

### ISSUE THREAD

**Issue by ghost** [pbs/pycaption#302]
Hi

I have been trying to convert from an SCC file to a vtt file. The file is 2 hours long and at the end, there seems to be a drift in the caption timing of around 6-8 seconds.

As a test, I am just running this:

from pycaption import (
    SCCReader, SCCWriter, SRTReader, SRTWriter, DFXPWriter, WebVTTWriter,detect_format
)

filename = "/mnt/storage/captions/OT197518.scc"
str = open(filename, 'r').read()

print(WebVTTWriter().write(SCCReader().read(str)))

The last 2 captions in the SCC look like this

![image](https://user-images.githubusercontent.com/60980627/231260623-61cb2ae7-fdfc-42d2-8a17-d0abebc7440a.png)

and the output looks like this:

![image](https://user-images.githubusercontent.com/60980627/231260759-1bc06cbe-9fed-45b2-b284-98e678e43ef2.png)

I have seen the exact same drift on a commercial product (Telestream) with the same 11 second stretch but loading the file into subedit yields what I would expect to see as a result.

I am not a fan of scc but that is the hand I have been dealt!

Everything else on the VTT writer looks great. 

Thank you for a great package.

Darren Breeze

**Comment by ksn-systems** [comment]
Thanks Ian
