### ISSUE TITLE
Captions does not keep style/position

### ISSUE THREAD

**Issue by Tama47** [pbs/pycaption#306]
### Expected behavior
![Expected behavior](https://cdn.discordapp.com/attachments/1082457187500171428/1125579519353426010/Screenshot_2023-07-03_at_17.10.23.png)

### Actual behavior
![Actual behavior](https://cdn.discordapp.com/attachments/1082457187500171428/1125579518820757565/mpv-shot0005.png)

Original vtt sub from Hidive
[bang-dreams01e001.english-subs.vtt](https://cdn.discordapp.com/attachments/1082457187500171428/1125744572849475694/bang-dreams01e001.english-subs.vtt)

Converted srt sub from pycaption
[bang-dreams01e001.english-subs.srt](https://cdn.discordapp.com/attachments/1082457187500171428/1125744573826736199/bang-dreams01e001.english-subs.srt)

**Comment by pacifier1er** [comment]
I'm sorry I do not.

**Comment by Tama47** [comment]
Alright, thanks.
