### ISSUE TITLE
Do not fail on empty WebVTT cue

### ISSUE THREAD

**Issue by shakkhar** [pbs/pycaption#42]
According to the spec empty cue is NOT a syntax error: http://dev.w3.org/html5/webvtt/#dfn-webvtt-cue-text. Emphasis mine.

> 4.3.2 WebVTT cue text
> 
> WebVTT cue text is cue payload that consists of **zero** or more WebVTT cue components, in any order, each optionally separated from the next by a WebVTT line terminator.

We should get rid of [this](https://github.com/pbs/pycaption/blob/master/pycaption/webvtt.py#L58-59) exception. Also check out the WebVTT [validator](http://quuz.org/webvtt/).

**Comment by ana-nichifor** [comment]
Hi, this was fixed on pycaption 1.0.4.
