### ISSUE TITLE
Align the WebVTT parser with spec

### ISSUE THREAD

**Issue by shakkhar** [pbs/pycaption#44]
Right now pycaption WebVTT perser passes texts like this:

```
WEBVTT

1
00:00.000 --> 00:02.000
cue text

id1 id2

00:04.000 --> 00:05.000
Transcribed by Celestials™
```

According to WebVTT spec line 7 shall be interpreted as a cue identifier and must be followed by a cue. Since line 8 is empty, above snippet is not valid WebVTT.

Lines such as line 7 above shall only pass when prefixed by the text `NOTE` as follows:

```
WEBVTT

1
00:00.000 --> 00:02.000
cue text

NOTE id1 id2

00:04.000 --> 00:05.000
Transcribed by Celestials™
```

In this case, line 7 shall be interpreted as a comment and ignored.

**Comment by pacifier1er** [comment]
This was handled here, https://github.com/pbs/pycaption/pull/215
